apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    name: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # change for your values
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "your-host-path"
  persistentVolumeReclaimPolicy: Retain